# __Chapter 8. Linear Algebraic Equations and Matrices__

- 행렬의 연산

In [1]:
import numpy as np

1. 행렬과 스칼라 생성

In [7]:
A = np.array([
    [1, 2, 0],
    [0, 1, 3],
    [2, 0, 1]
], dtype=float)

B = np.array([
    [2, 0, 1],
    [1, 3, 0],
    [0, 1, 2]
], dtype=float)

C = np.array([
    [0, 1, 2],
    [2, 0, 1],
    [1, 2, 0]
], dtype=float)

O = np.zeros_like(A)  # 영행렬
I = np.eye(3)         # 단위행렬

alpha = 2
beta = 3

2. 행렬 출력

In [8]:
for name, matrix in [("A", A), ("B", B), ("C", C)]:
    print(f"{name} =\n{matrix}\n")

A =
[[1. 2. 0.]
 [0. 1. 3.]
 [2. 0. 1.]]

B =
[[2. 0. 1.]
 [1. 3. 0.]
 [0. 1. 2.]]

C =
[[0. 1. 2.]
 [2. 0. 1.]
 [1. 2. 0.]]



3. 두 계산 결과를 비교하는 함수

In [9]:
def check_law(name, lhs, rhs):
    # 부동소수점 계산 오차를 고려하여 비교
    equal = np.allclose(lhs, rhs, rtol=1e-10, atol=1e-12)
    print(f"{name}: {'같음' if equal else '다름'}")

4. 기본 연산 결과

In [10]:
print("=" * 60)
print("기본 연산")
print("=" * 60)

operations = [
    ("A + B", A + B),
    ("A - B", A - B),
    ("alpha * A", alpha * A),
    ("A @ B", A @ B),
    ("B @ A", B @ A),
]

for expression, result in operations:
    print(f"\n{expression} =\n{result}")

기본 연산

A + B =
[[3. 2. 1.]
 [1. 4. 3.]
 [2. 1. 3.]]

A - B =
[[-1.  2. -1.]
 [-1. -2.  3.]
 [ 2. -1. -1.]]

alpha * A =
[[2. 4. 0.]
 [0. 2. 6.]
 [4. 0. 2.]]

A @ B =
[[4. 6. 1.]
 [1. 6. 6.]
 [4. 1. 4.]]

B @ A =
[[4. 4. 1.]
 [1. 5. 9.]
 [4. 1. 5.]]


5. 덧셈의 연산법칙

In [11]:
print("\n" + "=" * 60)
print("덧셈의 연산법칙")
print("=" * 60)

check_law("교환법칙: A + B = B + A",
          A + B, B + A)

check_law("결합법칙: (A + B) + C = A + (B + C)",
          (A + B) + C, A + (B + C))

check_law("덧셈의 항등원: A + O = A",
          A + O, A)

check_law("덧셈의 역원: A + (-A) = O",
          A + (-A), O)



덧셈의 연산법칙
교환법칙: A + B = B + A: 같음
결합법칙: (A + B) + C = A + (B + C): 같음
덧셈의 항등원: A + O = A: 같음
덧셈의 역원: A + (-A) = O: 같음


6. 뺄셈의 연산법칙

In [12]:
print("\n" + "=" * 60)
print("뺄셈의 연산법칙")
print("=" * 60)

check_law("뺄셈의 정의: A - B = A + (-B)",
          A - B, A + (-B))

check_law("부호 관계: A - B = -(B - A)",
          A - B, -(B - A))

check_law("괄호 전개: A - (B + C) = A - B - C",
          A - (B + C), A - B - C)

check_law("괄호 전개: A - (B - C) = A - B + C",
          A - (B - C), A - B + C)

# 다음 두 법칙은 일반적으로 성립하지 않음
check_law("교환법칙 확인: A - B vs B - A",
          A - B, B - A)

check_law("결합법칙 확인: (A - B) - C vs A - (B - C)",
          (A - B) - C, A - (B - C))


뺄셈의 연산법칙
뺄셈의 정의: A - B = A + (-B): 같음
부호 관계: A - B = -(B - A): 같음
괄호 전개: A - (B + C) = A - B - C: 같음
괄호 전개: A - (B - C) = A - B + C: 같음
교환법칙 확인: A - B vs B - A: 다름
결합법칙 확인: (A - B) - C vs A - (B - C): 다름


7. 스칼라 곱의 연산법칙

In [13]:
print("\n" + "=" * 60)
print("스칼라 곱의 연산법칙")
print("=" * 60)

check_law("분배법칙: alpha*(A + B) = alpha*A + alpha*B",
          alpha * (A + B), alpha * A + alpha * B)

check_law("분배법칙: (alpha + beta)*A = alpha*A + beta*A",
          (alpha + beta) * A, alpha * A + beta * A)

check_law("결합법칙: alpha*(beta*A) = (alpha*beta)*A",
          alpha * (beta * A), (alpha * beta) * A)

check_law("스칼라 1: 1*A = A",
          1 * A, A)

check_law("스칼라 0: 0*A = O",
          0 * A, O)


스칼라 곱의 연산법칙
분배법칙: alpha*(A + B) = alpha*A + alpha*B: 같음
분배법칙: (alpha + beta)*A = alpha*A + beta*A: 같음
결합법칙: alpha*(beta*A) = (alpha*beta)*A: 같음
스칼라 1: 1*A = A: 같음
스칼라 0: 0*A = O: 같음


8. 행렬 곱셈의 연산법칙

In [14]:
print("\n" + "=" * 60)
print("행렬 곱셈의 연산법칙")
print("=" * 60)

check_law("결합법칙: (AB)C = A(BC)",
          (A @ B) @ C, A @ (B @ C))

check_law("분배법칙: A(B + C) = AB + AC",
          A @ (B + C), A @ B + A @ C)

check_law("분배법칙: (A + B)C = AC + BC",
          (A + B) @ C, A @ C + B @ C)

check_law("뺄셈에 대한 분배법칙: A(B - C) = AB - AC",
          A @ (B - C), A @ B - A @ C)

check_law("스칼라 곱과의 관계: alpha*(AB) = (alpha*A)B",
          alpha * (A @ B), (alpha * A) @ B)

check_law("스칼라 곱과의 관계: alpha*(AB) = A(alpha*B)",
          alpha * (A @ B), A @ (alpha * B))

check_law("단위행렬: AI = A",
          A @ I, A)

check_law("단위행렬: IA = A",
          I @ A, A)

check_law("영행렬: AO = O",
          A @ O, O)

# 행렬 곱셈의 교환법칙은 일반적으로 성립하지 않음
check_law("교환법칙 확인: AB vs BA",
          A @ B, B @ A)


행렬 곱셈의 연산법칙
결합법칙: (AB)C = A(BC): 같음
분배법칙: A(B + C) = AB + AC: 같음
분배법칙: (A + B)C = AC + BC: 같음
뺄셈에 대한 분배법칙: A(B - C) = AB - AC: 같음
스칼라 곱과의 관계: alpha*(AB) = (alpha*A)B: 같음
스칼라 곱과의 관계: alpha*(AB) = A(alpha*B): 같음
단위행렬: AI = A: 같음
단위행렬: IA = A: 같음
영행렬: AO = O: 같음
교환법칙 확인: AB vs BA: 다름


---

- 피봇 행렬의 활용

> - 행을 바꾸려면 PA

In [15]:
import numpy as np

# 원래 행렬
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 1행과 3행을 바꾸는 피봇행렬
P = np.array([
    [0, 0, 1],
    [0, 1, 0],
    [1, 0, 0]
])

# 행 교환
B = P @ A

print("A =")
print(A)

print("\nP =")
print(P)

print("\nP @ A =")
print(B)

A =
[[1 2 3]
 [4 5 6]
 [7 8 9]]

P =
[[0 0 1]
 [0 1 0]
 [1 0 0]]

P @ A =
[[7 8 9]
 [4 5 6]
 [1 2 3]]


> - 열을 바꾸려면 AP

In [16]:
import numpy as np

# 원래 행렬
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 1열과 3열을 바꾸는 기본행렬
P = np.array([
    [0, 0, 1],
    [0, 1, 0],
    [1, 0, 0]
])

# 열 교환
C = A @ P

print("A =")
print(A)

print("\nP =")
print(P)

print("\nA @ P =")
print(C)

A =
[[1 2 3]
 [4 5 6]
 [7 8 9]]

P =
[[0 0 1]
 [0 1 0]
 [1 0 0]]

A @ P =
[[3 2 1]
 [6 5 4]
 [9 8 7]]


---

- 행렬의 확장(augmentation)

In [18]:
import numpy as np

# 계수행렬 A
A = np.array([
    [1, 2, 3],
    [3, 4, 5],
    [5, 6, 7]
])

# 추가할 열 벡터 b
b = np.array([7, 8, 9])

# 열 추가: augmented matrix [A | b]
Aug = np.column_stack((A, b))

print("A =")
print(A)

print("\nb =")
print(b)

print("\n[A | b] =")
print(Aug)

A =
[[1 2 3]
 [3 4 5]
 [5 6 7]]

b =
[7 8 9]

[A | b] =
[[1 2 3 7]
 [3 4 5 8]
 [5 6 7 9]]


---

- 예제 8.2 - 번지점프 문제

In [19]:
import numpy as np

A = np.array([
    [150, -100,   0],
    [-100, 150, -50],
    [0,    -50,  50]
], dtype=float)

b = np.array([588.6, 686.7, 784.8])

x = np.linalg.solve(A, b)

print("Solution x =")
print(x)

Solution x =
[41.202 55.917 71.613]


In [21]:
# inv(A)를 사용할 수도 있으나 solve()가 더 효율적이고 안정적
x = np.linalg.inv(A) @ b

print("Solution x =")
print(x)

Solution x =
[41.202 55.917 71.613]
